# Generated by Django 4.1.1 on 2022-10-03 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('documento_auxiliar', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('no_tarjetaprof', models.IntegerField(default=0)),
                ('turno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('documento_enfermero', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=30)),
                ('segundo_apellido', models.CharField(max_length=30)),
                ('turno', models.IntegerField(default=0)),
                ('area_trabajo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('documento_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('no_tarjetaprof', models.IntegerField(default=0)),
                ('especialidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(default=0)),
                ('documento_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('documento_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='agildevhealtapp.auxiliar')),
                ('documento_enfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='agildevhealtapp.enfermero')),
                ('documento_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='agildevhealtapp.medicos')),
            ],
        ),
        migrations.CreateModel(
            name='Signosvitales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperatura', models.CharField(max_length=45)),
                ('presion_arterial', models.CharField(max_length=45)),
                ('oximetriua', models.CharField(max_length=45)),
                ('frecuencia_cardiaca', models.CharField(max_length=45)),
                ('glicemias', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_signosvitales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('documento_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rsignosvitales', to='agildevhealtapp.medicos')),
                ('documento_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rsignosvitales', to='agildevhealtapp.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id_historia_clinica', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(max_length=30)),
                ('histroia_clinica', models.CharField(max_length=300)),
                ('diagnostico', models.CharField(max_length=300)),
                ('sugerencias', models.CharField(max_length=300)),
                ('documento_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='agildevhealtapp.medicos')),
                ('documento_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiaclinica', to='agildevhealtapp.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=60)),
                ('telefono', models.IntegerField(default=0)),
                ('documento_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to='agildevhealtapp.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('lastChangeDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
